name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
